lib/mcrz_his/web/router.ex
defmodule His.Web.Router do
  use His.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug His.Sessions.Login
  end

  pipeline :auth do
    plug His.Sessions.Logged
  end

  pipeline :admin do
    plug His.Sessions.AdminOnly
  end

  scope "/admin", His.Web do
    pipe_through [:browser, :auth, :admin]

    resources "/mkb", MkbController, param: "code" do
      resources "/sub_code", MkbSubsController, param: "code", as: "subs"
    end

    scope "/complaints" do
      resources "/categories", ComplaintCategoriesController do
        resources "/c", ComplaintsController
      end
    end

    resources "/users", UserController
  end

  scope "/dashboard", His.Web do
    pipe_through [:browser, :auth]

    get "/", DashboardController, :show

    scope "/resources" do
      resources "/patients", PatientController do
        resources "/visitations", VisitationController
        get "/visitations/:id/instructions", VisitationController, :instructions
        put "/visitations/:id/instructions", VisitationController, :instructions_update
        get "/visitations/:id/print",        VisitationController, :print
        resources "/documents", DocumentController
        get "/documents/:id/print", DocumentController, :print
      end
    end
  end

  scope "/", His.Web do
    pipe_through :browser

    get "/", PageController, :index

    resources "/registration", RegistrationController,
      only: [:new, :create], singleton: true

    post "/session/create", SessionController, :create
    get  "/session/delete", SessionController, :delete

    get  "/email/verify", EmailController, :verify

    get  "/password/new", PasswordController, :show
    post "/password/new", PasswordController, :update
    put  "/password/new", PasswordController, :update

    get  "/password/reset", PasswordResetController, :show
    post "/passwrod/reset", PasswordResetController, :create
  end

  scope "/" do
    if Mix.env == :dev do
      forward "/sent_emails", Bamboo.EmailPreviewPlug
    end
  end
end

lib/mcrz_his/web/controllers/dashboard_controller.ex
defmodule His.Web.DashboardController do
  use His.Web, :controller

  def show(conn, _params, current_user) do
    current_user = current_user |> His.Repo.preload(visitations: His.Patients.visitation_query(:patient))
    render conn, "show.html", user: current_user
  end

  def action(conn, _params) do
    current_user = conn.assigns[:current_user]
    apply(__MODULE__, action_name(conn), [conn, conn.params, current_user])
  end
end

lib/mcrz_his/web/views/dashboard_view.ex
defmodule His.Web.DashboardView do
  use His.Web, :view

  def tr_position("doctor"), do: "доктор"
  def tr_position("nurse"), do: "мед. сестра"
  def tr_position("admin"), do: "администратор"
  def tr_position("registrar"), do: "регистратор"
end

lib/mcrz_his/web/templates/dashboard/show.html.eex
<div class="content">
<div class="card" style="width: 20rem;">
    <div class="card-block">
        <h4 class="card-title"><%= lfm(@user) %></h4>
        <p class="card-text"> <%= @user.email %> </p>
        <p class="card-text">
          <span class="label label-info"><%= tr_position(@user.position) %> </span>
        </p>
    </div>
</div>
<h2>Приемы</h2>
<table class="table">
  <thead>
    <tr>
      <th>Имя</th>
      <th>Дата</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for visitation <- @user.visitations do %>
  <tr class="<%= if visitation.first, do: "first" %>">
      <td><%= link His.Web.DocumentView.full_name(visitation.patient), to: patient_path(@conn, :show, visitation.patient) %> </td>
      <td><%= visitation.inserted_at |> format_time() %> </td>

      <td class="text-right">
        <span><%= link "Редактировать", to: patient_visitation_path(@conn, :edit, visitation.patient, visitation), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Удалить", to: patient_visitation_path(@conn, :delete, visitation.patient, visitation), method: :delete, data: [confirm: "Вы уверены?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>
</div>