lib/mcrz_his/web/router.ex
defmodule His.Web.Router do
  use His.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug His.Sessions.Login
  end

  pipeline :auth do
    plug His.Sessions.Logged
  end

  pipeline :admin do
    plug His.Sessions.AdminOnly
  end

  scope "/admin", His.Web do
    pipe_through [:browser, :auth, :admin]

    resources "/mkb", MkbController, param: "code" do
      resources "/sub_code", MkbSubsController, param: "code", as: "subs"
    end

    scope "/complaints" do
      resources "/categories", ComplaintCategoriesController do
        resources "/c", ComplaintsController
      end
    end

    resources "/users", UserController
  end

  scope "/dashboard", His.Web do
    pipe_through [:browser, :auth]

    get "/", DashboardController, :show

    scope "/resources" do
      resources "/patients", PatientController do
        resources "/visitations", VisitationController
        get "/visitations/:id/instructions", VisitationController, :instructions
        put "/visitations/:id/instructions", VisitationController, :instructions_update
        get "/visitations/:id/print",        VisitationController, :print
        resources "/documents", DocumentController
        get "/documents/:id/print", DocumentController, :print
      end
    end
  end

  scope "/", His.Web do
    pipe_through :browser

    get "/", PageController, :index

    resources "/registration", RegistrationController,
      only: [:new, :create], singleton: true

    post "/session/create", SessionController, :create
    get  "/session/delete", SessionController, :delete

    get  "/email/verify", EmailController, :verify

    get  "/password/new", PasswordController, :show
    post "/password/new", PasswordController, :update
    put  "/password/new", PasswordController, :update

    get  "/password/reset", PasswordResetController, :show
    post "/passwrod/reset", PasswordResetController, :create
  end

  scope "/" do
    if Mix.env == :dev do
      forward "/sent_emails", Bamboo.EmailPreviewPlug
    end
  end
end

lib/mcrz_his/web/views/layout_view.ex
defmodule His.Web.LayoutView do
  use His.Web, :view
end

lib/mcrz_his/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>MCRZ HIS</title>
    <script
        src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>
    <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
            <ul class="nav nav-pills pull-right" style="margin-top: 0;">
                <%= if logged_in?(@conn) do %>
                    <%= if is_admin?(@current_user) do %>
                        <div class="btn-group actions">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Редактировать <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><%= link "МКБ", to: mkb_path(@conn, :index) %></li>
                                <li><%= link "Жалобы", to: complaint_categories_path(@conn, :index) %></li>
                    <li><%= link "Пользователи", to: user_path(@conn, :index)%></li>
                            </ul>
                        </div>
                <% end %>
                <li><%= link "Пациенты", to: patient_path(@conn, :index), class: "btn btn-info" %></li>
                <li><%= link "Выход", to: session_path(@conn, :delete) %></li>
              <% end %>
          </ul>
        </nav>
        <% path = if logged_in?(@conn), do: dashboard_path(@conn, :show), else: page_path(@conn, :index) %>
        <a href="<%= path %>"><h1>МЦРЗ МИС</h1></a>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script>
</script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/mcrz_his/web/templates/layout/document.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link rel="stylesheet" href="https://unpkg.com/gutenberg-css@0.4" media="print">
    <link rel="stylesheet" href="https://unpkg.com/gutenberg-css@0.4/dist/themes/old.min.css" media="print">
    <style>
     table,th,td{border-bottom:0px solid #000}
     .child_value{margin-left: 8px; margin-right: 8px;}
    </style>
  </head>
  <body>
    <%= render @view_module, @view_template, assigns %>
  </body>
</html>