lib/mcrz_his/web/router.ex
defmodule His.Web.Router do
  use His.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug His.Sessions.Login
  end

  pipeline :auth do
    plug His.Sessions.Logged
  end

  pipeline :admin do
    plug His.Sessions.AdminOnly
  end

  scope "/admin", His.Web do
    pipe_through [:browser, :auth, :admin]

    resources "/mkb", MkbController, param: "code" do
      resources "/sub_code", MkbSubsController, param: "code", as: "subs"
    end

    scope "/complaints" do
      resources "/categories", ComplaintCategoriesController do
        resources "/c", ComplaintsController
      end
    end

    resources "/users", UserController
  end

  scope "/dashboard", His.Web do
    pipe_through [:browser, :auth]

    get "/", DashboardController, :show

    scope "/resources" do
      resources "/patients", PatientController do
        resources "/visitations", VisitationController
        get "/visitations/:id/instructions", VisitationController, :instructions
        put "/visitations/:id/instructions", VisitationController, :instructions_update
        get "/visitations/:id/print",        VisitationController, :print
        resources "/documents", DocumentController
        get "/documents/:id/print", DocumentController, :print
      end
    end
  end

  scope "/", His.Web do
    pipe_through :browser

    get "/", PageController, :index

    resources "/registration", RegistrationController,
      only: [:new, :create], singleton: true

    post "/session/create", SessionController, :create
    get  "/session/delete", SessionController, :delete

    get  "/email/verify", EmailController, :verify

    get  "/password/new", PasswordController, :show
    post "/password/new", PasswordController, :update
    put  "/password/new", PasswordController, :update

    get  "/password/reset", PasswordResetController, :show
    post "/passwrod/reset", PasswordResetController, :create
  end

  scope "/" do
    if Mix.env == :dev do
      forward "/sent_emails", Bamboo.EmailPreviewPlug
    end
  end
end

lib/mcrz_his/web/controllers/patient_controller.ex
defmodule His.Web.PatientController do
  use His.Web, :controller

  alias His.Patients

  def index(conn, _params) do
    patients = Patients.list_patients()
    render(conn, "index.html", patients: patients)
  end

  def new(conn, _params) do
    changeset = Patients.change_patient(%His.Patients.Patient{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"patient" => patient_params}) do
    case Patients.create_patient(patient_params) do
      {:ok, patient} ->
        conn
        |> put_flash(:info, "Пациент создан успешно.")
        |> redirect(to: patient_path(conn, :show, patient))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    patient = Patients.get_patient!(id)
    render(conn, "show.html", patient: patient)
  end

  def edit(conn, %{"id" => id}) do
    patient = Patients.get_patient!(id)
    changeset = Patients.change_patient(patient)
    render(conn, "edit.html", patient: patient, changeset: changeset)
  end

  def update(conn, %{"id" => id, "patient" => patient_params}) do
    patient = Patients.get_patient!(id)

    case Patients.update_patient(patient, patient_params) do
      {:ok, patient} ->
        conn
        |> put_flash(:info, "Пациент обновлен успешно.")
        |> redirect(to: patient_path(conn, :show, patient))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", patient: patient, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    patient = Patients.get_patient!(id)
    case Patients.delete_patient(patient) do
      {:ok, _patient} -> 
        conn
        |> put_flash(:info, "Пациент удален успешно.")
        |> redirect(to: patient_path(conn, :index))
      {:error, changeset = %Ecto.Changeset{action: :delete}} ->
        conn
        |> put_flash(:error, "Не удалось удалить пациента. " <>
                             "Возможно пациент имеет посещения или документы.")
        |> redirect(to: patient_path(conn, :index))
    end
  end
end

lib/mcrz_his/web/views/patient_view.ex
defmodule His.Web.PatientView do
  use His.Web, :view

  def current_year, do: Date.utc_today |> Map.get(:year)
end

lib/mcrz_his/web/templates/patient/edit.html.eex
<h2>Редактировать данные пациента</h2>

<%= render "form.html", changeset: @changeset,
                        action: patient_path(@conn, :update, @patient) %>

<span><%= link "Назад", to: patient_path(@conn, :index) %></span>

lib/mcrz_his/web/templates/patient/form.html.eex
<%= form_for @changeset, @action, [multipart: true], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= label f, "Фамилия", class: "control-label" %>
    <%= text_input f, :last_name, class: "form-control" %>
    <%= error_tag f, :last_name %>
  </div>

  <div class="form-group">
    <%= label f, "Имя", class: "control-label" %>
    <%= text_input f, :first_name, class: "form-control" %>
    <%= error_tag f, :first_name %>
  </div>

  <div class="form-group">
    <%= label f, "Отчество", class: "control-label" %>
    <%= text_input f, :middle_name, class: "form-control" %>
    <%= error_tag f, :middle_name %>
  </div>

  <div class="form-group">
    <%= label f, :code, class: "control-label" %>
    <%= text_input f, :code, class: "form-control" %>
    <%= error_tag f, :code %>
  </div>

  <div class="form-group">
    <%= label f, "Адрес", class: "control-label" %>
    <%= text_input f, :address, class: "form-control" %>
    <%= error_tag f, :address %>
  </div>

  <div class="form-group">
    <%= label f, "Номер телефона", class: "control-label" %>
    <%= text_input f, :phone_number, class: "form-control" %>
    <%= error_tag f, :phone_number %>
  </div>

  <div class="form-group">
    <%= label f, "Дата рождения", class: "control-label" %>
    <%= date_select f, :birthday, year: [options: 1900..current_year()], class: "form-control" %>
    <%= error_tag f, :birthday %>
  </div>

  <div class="form-group">
    <%= submit "Сохранить", class: "btn btn-primary" %>
  </div>
<% end %>

lib/mcrz_his/web/templates/patient/index.html.eex
<h2>Список пациентов</h2>

<table class="table">
  <thead>
    <tr>
      <th>Имя</th>
      <th>Отчество</th>
      <th>Фамилия</th>
      <th>Code</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for patient <- @patients do %>
    <tr>
      <td><%= patient.first_name %></td>
      <td><%= patient.middle_name %></td>
      <td><%= patient.last_name %></td>
      <td><%= patient.code %></td>

      <td class="text-right">
        <span><%= link "Показать", to: patient_path(@conn, :show, patient), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Редактировать", to: patient_path(@conn, :edit, patient), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Удалить", to: patient_path(@conn, :delete, patient), method: :delete, data: [confirm: "Вы уверены?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "Добавить пациента", to: patient_path(@conn, :new) %></span>

lib/mcrz_his/web/templates/patient/new.html.eex
<h2>Новый пациент</h2>

<%= render "form.html", changeset: @changeset,
                        action: patient_path(@conn, :create) %>

<span><%= link "Назад", to: patient_path(@conn, :index) %></span>

lib/mcrz_his/web/templates/patient/show.html.eex
<h2>Данные пациента</h2>

<ul>

  <li>
    <strong>Email:</strong>
    <%= @patient.email %>
  </li>

  <li>
    <strong>Фамилия:</strong>
    <%= @patient.last_name %>
  </li>

  <li>
    <strong>Имя:</strong>
    <%= @patient.first_name %>
  </li>

  <li>
    <strong>Отчество:</strong>
    <%= @patient.middle_name %>
  </li>

  <li>
    <strong>Код:</strong>
    <%= @patient.code %>
  </li>

  <li>
    <strong>Адрес:</strong>
    <%= @patient.address %>
  </li>

  <li>
    <strong>Номер телефона:</strong>
    <%= @patient.phone_number %>
  </li>

  <li>
    <strong>Дата рождения:</strong>
    <%= @patient.birthday %>
  </li>

  <li>
    <strong>Первое посещение:</strong>
    <%= @patient.first_visit %>
  </li>
  <li>
    <%= link "Документы", to: patient_document_path(@conn, :index, @patient) %>
  </li>
  <li>
    <%= link "Посещения", to: patient_visitation_path(@conn, :index, @patient) %>
  </li>
</ul>

<span><%= link "Редактировать", to: patient_path(@conn, :edit, @patient) %></span>
<span><%= link "Назад", to: patient_path(@conn, :index) %></span>